[package]
name = "toss"
version = "0.2.0"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
crossterm = "0.27.0"
unicode-linebreak = "0.1.5"
unicode-segmentation = "1.10.1"
unicode-width = "0.1.11"
