[package]
name = "toss"
version = "0.2.2"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
crossterm = "0.27.0"
unicode-linebreak = "0.1.5"
unicode-segmentation = "1.11.0"
unicode-width = "0.1.11"
